### ISSUE TITLE
any way to make assertions on async functions?

### ISSUE THREAD

**Issue by nikhedonia** [joakimkarlsson/igloo#19]
Let's consider following example:
```c++
#include <future>
template<class Callback>
auto  toTest(Callback F,...){
  //some stuff
  std::async(std::launch::async, [=](){
    //expensive computation
    int result = 42;
    F(result);
  }):
}
```

What is the idiomatic way to test for the result?
Throwing exceptions within the callback is not sufficient, because the callback may not be called at all.

**Comment by joakimkarlsson** [comment]
There's no built-in support for this in igloo. But if you change your code to just returning the `std::future` from `toTest()` instead of the callback, you could use `std::future::wait_until()` to wait for the async job to finish or a time out before you assert.

Even better would perhaps be looking at the possibility of extracting the async method so you can test that separately from the `toTest` method without the async stuff in the way.
